cam0:
  T_cam_imu:
  - [0.7114001955330131, 0.7025631268725394, -0.017743014249865907, 
      -0.0018165475308931783]
  - [-0.01763063032492551, -0.0073976797008822315, -0.9998172008969387, 
      -0.004209844565692009]
  - [-0.7025659560994516, 0.7115829727404414, 0.007123919984115185, 
      -0.035256014398197213]
  - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
  - [0.711400195533013, -0.017630630324925317, -0.7025659560994514, 
      -0.02355160540851614]
  - [0.7025631268725392, -0.007397679700882149, 0.7115829727404409, 
      0.026332675764178373]
  - [-0.017743014249866088, -0.9998172008969382, 0.007123919984115257, 
      -0.003990145013075995]
  - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
  - [0.001172087934522266, 0.00884457185386911, -0.9999601990872413, 
      -0.032778869472619744]
  - [0.016437982464159166, 0.9998256078868971, 0.008862648932725132, 
      0.0002719305565125064]
  - [0.9998642002504048, -0.016447716021335136, 0.0010264966145937526, 
      -0.032381715411769575]
  - [0.0, 0.0, 0.0, 1.0]
  distortion_coeffs: [-0.061363941622975586, 0.5382466059560416, 
      -0.0040446666544682085, -0.00014407483758505674, 0.0]
  intrinsics: [3.2500196200650535, 1678.260181160915, 1677.967287422277, 
      547.1605405763067, 599.9779574795629]
  resolution: [1088, 1280]
  camera_model: omni
  distortion_model: radtan
  timeshift_cam_imu: 0.0
  rostopic: /fisheye/left/image_raw
cam1:
  T_cam_imu:
  - [0.6968147689588883, -0.7170079570935628, 0.018675310580738846, 
      0.0028638365973200283]
  - [0.009133742825045144, -0.017164737289144832, -0.9998109553989698, 
      -0.0037213378531687816]
  - [0.7171929674102899, 0.6968536153729208, -0.0054116761647719225, 
      -0.03439598571040391]
  - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
  - [0.6968147689588882, 0.009133742825044979, 0.7171929674102899, 
      0.022706985164664895]
  - [-0.7170079570935625, -0.017164737289144742, 0.6968536153729206, 
      0.0259584848380907]
  - [0.018675310580739016, -0.9998109553989697, -0.005411676164771862, 
      -0.003960257328279295]
  - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
  - [-0.008360545742253773, -0.02565298513761653, -0.9996359465467523, 
      -0.032502525135888256]
  - [0.012178094958693885, 0.9995941364384753, -0.025753764792667402, 
      -0.0003990549239955411]
  - [0.9998908916867225, -0.012388977009754524, -0.008044748012402625, 
      -0.032915417799242105]
  - [0.0, 0.0, 0.0, 1.0]
  distortion_coeffs: [-0.02367971769020006, 0.3097039713497103, 
      0.002842969910500867, -0.0023826147164189345, 0.0]
  intrinsics: [3.2014984644644926, 1663.3279482337853, 1663.6314003744023, 
      545.964878154349, 621.5124135931073]
  resolution: [1088, 1280]
  camera_model: omni
  distortion_model: radtan
  timeshift_cam_imu: 0.0
  rostopic: /fisheye/right/image_raw
cam2:
  T_cam_imu:
  - [-0.7153693238280376, -0.6985639897508351, -0.015971310190834198, 
      0.0014473308069009108]
  - [0.008451958129050141, 0.014204649643235534, -0.9998633868345704, 
      -0.004045934902964594]
  - [0.6986954235785443, -0.7154065838052571, -0.004257337018659602, 
      -0.029580518246759842]
  - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
  - [-0.7153693238280373, 0.008451958129049997, 0.698695423578544, 
      0.02173734485917363]
  - [-0.6985639897508349, 0.01420464964323581, -0.7154065838052569, 
      -0.020093573235369578]
  - [-0.015971310190834094, -0.9998633868345703, -0.0042573370186593075, 
      -0.00414820064108767]
  - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
  - [0.0020977599086679784, 0.02142495883583008, -0.9997682584190443, 
      -0.03286696205467649]
  - [-0.02296815685842836, 0.9995077469920297, 0.021371183248556806, 
      0.000474431072268237]
  - [0.9997339962079376, 0.022918002570026724, 0.0025888190952696455, 
      -0.03226926243759453]
  - [0.0, 0.0, 0.0, 1.0]
  distortion_coeffs: [-0.07222973486381698, 0.536469869618508, 
      -0.0009144962811252404, -0.0012504589250424865, 0.0]
  intrinsics: [3.1983572693768383, 1651.5812210080965, 1651.459594150425, 
      545.2080309272277, 656.832122013611]
  resolution: [1088, 1280]
  camera_model: omni
  distortion_model: radtan
  timeshift_cam_imu: 0.0
  rostopic: /fisheye/bright/image_raw
cam3:
  T_cam_imu:
  - [-0.7019265362248521, 0.7121882027859748, -0.009332821431067062, 
      -0.0029112894342394682]
  - [0.00022007979638172248, -0.012886434207635689, -0.999916942239852, 
      -0.004159869401305094]
  - [-0.7122493168183907, -0.7018702897444051, 0.00888859189300073, 
      -0.03100376047073472]
  - [0.0, 0.0, 0.0, 1.0]
  T_imu_cam:
  - [-0.7019265362248523, 0.0002200797963816568, -0.7122493168183911, 
      -0.024125003019394752]
  - [0.712188202785975, -0.012886434207635859, -0.7018702897444051, 
      -0.019740838238152182]
  - [-0.00933282143106699, -0.999916942239852, 0.008888591893000564, 
      -0.003911114662321318]
  - [0.0, 0.0, 0.0, 1.0]
  T_cn_cnm1:
  - [0.004776736590514541, 0.013515276651568958, -0.9998972547639963, 
      -0.03244100001216694]
  - [0.02481454420820528, 0.9995991532433599, 0.013629792034253595, 
      0.0002517051594530946]
  - [0.9996806596024971, -0.024877100558335412, 0.004439446421188431, 
      -0.032419959090006535]
  - [0.0, 0.0, 0.0, 1.0]
  distortion_coeffs: [-0.057344444583834676, 0.4428623934722441, 
      -0.004202533717592267, 0.00017514469629016226, 0.0]
  intrinsics: [3.1980582501254844, 1658.4738903617222, 1658.432571152381, 
      539.9428043888415, 595.8845689657935]
  resolution: [1088, 1280]
  camera_model: omni
  distortion_model: radtan
  timeshift_cam_imu: 0.0
  rostopic: /fisheye/bleft/image_raw
